// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/todo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_proto_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type TodoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoId) Reset() {
	*x = TodoId{}
	mi := &file_proto_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoId) ProtoMessage() {}

func (x *TodoId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoId.ProtoReflect.Descriptor instead.
func (*TodoId) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TodoTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoTitle) Reset() {
	*x = TodoTitle{}
	mi := &file_proto_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoTitle) ProtoMessage() {}

func (x *TodoTitle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoTitle.ProtoReflect.Descriptor instead.
func (*TodoTitle) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{2}
}

func (x *TodoTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type TodoStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoStatus) Reset() {
	*x = TodoStatus{}
	mi := &file_proto_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoStatus) ProtoMessage() {}

func (x *TodoStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoStatus.ProtoReflect.Descriptor instead.
func (*TodoStatus) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{3}
}

func (x *TodoStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoStatus) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_proto_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{4}
}

func (x *RenameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{5}
}

type TodoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoList) Reset() {
	*x = TodoList{}
	mi := &file_proto_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoList) ProtoMessage() {}

func (x *TodoList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoList.ProtoReflect.Descriptor instead.
func (*TodoList) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{6}
}

func (x *TodoList) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_proto_todo_proto protoreflect.FileDescriptor

const file_proto_todo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/todo.proto\x12\x04todo\"J\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"\x18\n" +
	"\x06TodoId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\tTodoTitle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\":\n" +
	"\n" +
	"TodoStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\"5\n" +
	"\rRenameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\a\n" +
	"\x05Empty\",\n" +
	"\bTodoList\x12 \n" +
	"\x05todos\x18\x01 \x03(\v2\n" +
	".todo.TodoR\x05todos2\x95\x02\n" +
	"\vTodoService\x12)\n" +
	"\n" +
	"CreateTodo\x12\x0f.todo.TodoTitle\x1a\n" +
	".todo.Todo\x12*\n" +
	"\vGetAllTodos\x12\v.todo.Empty\x1a\x0e.todo.TodoList\x12#\n" +
	"\aGetTodo\x12\f.todo.TodoId\x1a\n" +
	".todo.Todo\x12'\n" +
	"\n" +
	"DeleteTodo\x12\f.todo.TodoId\x1a\v.todo.Empty\x12.\n" +
	"\n" +
	"RenameTodo\x12\x13.todo.RenameRequest\x1a\v.todo.Empty\x121\n" +
	"\x10UpdateTodoStatus\x12\x10.todo.TodoStatus\x1a\v.todo.EmptyB\x14Z\x12todoapp-backend/pbb\x06proto3"

var (
	file_proto_todo_proto_rawDescOnce sync.Once
	file_proto_todo_proto_rawDescData []byte
)

func file_proto_todo_proto_rawDescGZIP() []byte {
	file_proto_todo_proto_rawDescOnce.Do(func() {
		file_proto_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_todo_proto_rawDesc), len(file_proto_todo_proto_rawDesc)))
	})
	return file_proto_todo_proto_rawDescData
}

var file_proto_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_todo_proto_goTypes = []any{
	(*Todo)(nil),          // 0: todo.Todo
	(*TodoId)(nil),        // 1: todo.TodoId
	(*TodoTitle)(nil),     // 2: todo.TodoTitle
	(*TodoStatus)(nil),    // 3: todo.TodoStatus
	(*RenameRequest)(nil), // 4: todo.RenameRequest
	(*Empty)(nil),         // 5: todo.Empty
	(*TodoList)(nil),      // 6: todo.TodoList
}
var file_proto_todo_proto_depIdxs = []int32{
	0, // 0: todo.TodoList.todos:type_name -> todo.Todo
	2, // 1: todo.TodoService.CreateTodo:input_type -> todo.TodoTitle
	5, // 2: todo.TodoService.GetAllTodos:input_type -> todo.Empty
	1, // 3: todo.TodoService.GetTodo:input_type -> todo.TodoId
	1, // 4: todo.TodoService.DeleteTodo:input_type -> todo.TodoId
	4, // 5: todo.TodoService.RenameTodo:input_type -> todo.RenameRequest
	3, // 6: todo.TodoService.UpdateTodoStatus:input_type -> todo.TodoStatus
	0, // 7: todo.TodoService.CreateTodo:output_type -> todo.Todo
	6, // 8: todo.TodoService.GetAllTodos:output_type -> todo.TodoList
	0, // 9: todo.TodoService.GetTodo:output_type -> todo.Todo
	5, // 10: todo.TodoService.DeleteTodo:output_type -> todo.Empty
	5, // 11: todo.TodoService.RenameTodo:output_type -> todo.Empty
	5, // 12: todo.TodoService.UpdateTodoStatus:output_type -> todo.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_todo_proto_init() }
func file_proto_todo_proto_init() {
	if File_proto_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todo_proto_rawDesc), len(file_proto_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todo_proto_goTypes,
		DependencyIndexes: file_proto_todo_proto_depIdxs,
		MessageInfos:      file_proto_todo_proto_msgTypes,
	}.Build()
	File_proto_todo_proto = out.File
	file_proto_todo_proto_goTypes = nil
	file_proto_todo_proto_depIdxs = nil
}
